### ISSUE TITLE
Online demo time picker not working

### ISSUE THREAD

**Issue by dsklur** [wojtekmaj/react-timerange-picker#1]
It does display a clock but it's not selectable.
Google chrome
Version 71.0.3578.98 (Official Build) (64-bit)

**Comment by wojtekmaj** [comment]
What do you mean? You can't do anything with the clock. Is there anything I describe in README what this package does, that it does not?

**Comment by dsklur** [comment]
http://projects.wojtekmaj.pl/react-timerange-picker/
http://projects.wojtekmaj.pl/react-time-picker/
It's not working

**Comment by wojtekmaj** [comment]
Ah. Well, it's a fair point, it would be a nice improvement! So far, no way to do it in [React-Clock](/wojtekmaj/react-clock), but maybe one day!
