### ISSUE TITLE
Unable to fetch AM/PM

### ISSUE THREAD

**Issue by sauzy34** [wojtekmaj/react-timerange-picker#17]
I'm trying to get the AM/PM with the range values from `onChange` event.

**Comment by wojtekmaj** [comment]
JavaScript does not use AM/PM in Date(), it uses military time. You'd need to manually convert the date to AM/PM.

You can use [this util](https://github.com/wojtekmaj/react-time-picker/blob/e4a9ca9cb180bd2c6a97f3dce7ddf06f07683bb8/src/shared/dates.js#L13-L17) to do this.
