### ISSUE TITLE
It is possible to have 3 digits in a row

### ISSUE THREAD

**Issue by bhanssens** [wojtekmaj/react-timerange-picker#21]
Hi,

Thanks for this nice component! It works great.
I've just noticed one thing. It is possible to enter 3 digits in the minutes input.

Way to reproduce: enter 0 in minutes. You can then add a third digit.

Do you have a quick workaround not to show this third digit without touching the internal logic?

Thanks.

**Comment by wojtekmaj** [comment]
Fixed in v3.2.0.
