### ISSUE TITLE
How to change input border color?

### ISSUE THREAD

**Issue by pablovejar** [wojtekmaj/react-timerange-picker#29]
Hello! 

Thanks for this work, it's amazing. is there any way that I can disable the square border of the time input?

**Comment by wojtekmaj** [comment]
Use Inspect to find the element you want to style and apply your own CSS either on top of the original styling, or replace the original styling altogether.

**Comment by rodrigo-galdeano-fivestars** [comment]
Hi, I'm also looking into this. Have you found a way? Thanks
