### ISSUE TITLE
Setting Value with Leading Zero

### ISSUE THREAD

**Issue by DerekFei** [wojtekmaj/react-timerange-picker#3]
if the value prop is "01:00:00", the displayed value will be 1:0:0AM.  Should be: 1:00:00AM or 01:00:00AM

**Comment by wojtekmaj** [comment]
Likely caused by React-Time-Picker 3.5.0 update. Fixed that in 3.5.1, so I'll be able to fix it here shortly.

In the meantime you could force React-Time-Picker to be version 3.4.0 or less.

**Comment by wojtekmaj** [comment]
Should be fixed by installing package again. Next version of React-TimeRange-Picker will have React-Time-Picker version locked above the one with the error you reported. Thank you!
