### ISSUE TITLE
Cannot render correctly

### ISSUE THREAD

**Issue by davidsu06** [wojtekmaj/react-timerange-picker#30]
I'm trying to render it's default shape, this is what I get.
![image](https://user-images.githubusercontent.com/57465385/102142933-2c26ec00-3e31-11eb-8766-4ce633bf85f2.png)

![image](https://user-images.githubusercontent.com/57465385/102142950-32b56380-3e31-11eb-8f78-3b395c624c28.png)

I tried importing TimeRangePicker.css but nothing changed

**Comment by wojtekmaj** [comment]
This looks more or less correct. The space here is because you might need an input for seconds, too.

You can edit the CSS yourself if you need React-TimeRange-Picker styling customized.
