### ISSUE TITLE
Possible component split?

### ISSUE THREAD

**Issue by billbarni** [wojtekmaj/react-timerange-picker#34]
Could this component be split up?

Something like:
```
<TimeRangePickerFrom group="rangeGroup1" />
<TimeRangePickerTo group="rangeGroup1" />
```

So people could organize them the way they wanted around any layout?

Thank you for all your amazing work on all the other beautiful components by the way.

**Comment by wojtekmaj** [comment]
In this case, I'd suggest using react-time-picker which is used internally by react-timerange-picker.
