### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by lyqht** [wojtekmaj/react-timerange-picker#37]
Hello there, I would like to request for Typescript support for this package

<img width="1157" alt="image" src="https://user-images.githubusercontent.com/35736525/186833994-a9ce9687-8b57-46d1-8665-ad4a86b0e905.png">

**Comment by wojtekmaj** [comment]
Feel free to contribute to DefinitelyTyped repo. React-Time-Picker is already there and may be the inspiration for you: https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/react-time-picker

**Comment by TiE23** [comment]
Ahh, no TypeScript is unfortunately a dealbreaker for me and I'm sure a lot of developers around. I'll just be using two react-time-picker components, then. Thanks for the work you've done!

**Comment by wojtekmaj** [comment]
Implemented in #169
