### ISSUE TITLE
i guess we have some security holes 

### ISSUE THREAD

**Issue by jhonyourangel** [wojtekmaj/react-timerange-picker#7]
<img width="534" alt="Screenshot 2019-07-15 at 08 44 38" src="https://user-images.githubusercontent.com/2562455/61199101-efefd900-a6dc-11e9-9ea4-465086af41f1.png">

**Comment by jhonyourangel** [comment]
this may have been an issue axios, instead of your lib

**Comment by wojtekmaj** [comment]
One security issue was recently reported in one of our devDependencies - you guessed it - lodash. Aside from that nothing looks wrong on `npm audit`.
